#include <stdio.h>

#define LOGGER_COLOR_RED        "\x1b[31m"
#define LOGGER_COLOR_GREEN      "\x1b[32m"
#define LOGGER_COLOR_YELLOW     "\x1b[33m"
#define LOGGER_COLOR_BLUE       "\x1b[34m"
#define LOGGER_COLOR_PURPLE     "\x1b[35m"
#define LOGGER_COLOR_CYAN       "\x1b[36m"
#define LOGGER_COLOR_WHITE      "\x1b[37m"
#define LOGGER_COLOR_RESET      "\x1b[0m"

int main() {
    printf(LOGGER_COLOR_RED "LOGGER_COLOR_RED" LOGGER_COLOR_RESET "\n");
    printf(LOGGER_COLOR_GREEN "LOGGER_COLOR_GREEN" LOGGER_COLOR_RESET "\n");
    printf(LOGGER_COLOR_YELLOW "LOGGER_COLOR_YELLOW" LOGGER_COLOR_RESET "\n");
    printf(LOGGER_COLOR_BLUE "LOGGER_COLOR_BLUE" LOGGER_COLOR_RESET "\n");
    printf(LOGGER_COLOR_PURPLE "LOGGER_COLOR_PURPLE" LOGGER_COLOR_RESET "\n");
    printf(LOGGER_COLOR_CYAN "LOGGER_COLOR_CYAN" LOGGER_COLOR_RESET "\n");
    printf(LOGGER_COLOR_WHITE "LOGGER_COLOR_WHITE" LOGGER_COLOR_RESET "\n");

    return 0;
}
